### ISSUE TITLE
[question] 4주차 백준 1783번 병든 나이트

### ISSUE THREAD

**Issue by dnwlsrla40** [psStudy6/psStudy#25]
## 질문 유형

문제의 설명이 이해가지 않습니다.

### 상세 내용

![image](https://user-images.githubusercontent.com/23308642/178456200-6f4f35dd-7edb-4e17-a3ee-4b19f44f26ee.png)

해당 내용 중 "이동 횟수가 4번보다 적은 경우(방문한 칸이 5개 미만)에는 이동 방법에 제약이 없다."라는 부분이 이해가 되질 않습니다.

바로 윗줄의 "이동 방법을 모두 한 번씩 사용해야 한다." 이 제약을 말하는 건지 아님, 1~4번의 이동 방식을 말하는 건지 모호하네요.

## 문제 출처

[백준 1783번 병든 나이트](https://www.acmicpc.net/problem/1783)

**Comment by hongcoding94** [comment]
- 풀이 완료 
[병든 나이트](https://github.com/psStudy6/psStudy/blob/main/src/week4/hong/BoJ1783%20.java)

**Comment by LeeJongbokz** [comment]
![image](https://user-images.githubusercontent.com/8718430/178882959-e1b1ef2a-2b32-4e06-97e7-cad554723ff7.png)
요 부분 확인하시면 좋을 것 같습니다~
