### ISSUE TITLE
[question] 4주차 백준 2477번 참외밭 

### ISSUE THREAD

**Issue by hongcoding94** [psStudy6/psStudy#28]
## 질문 유형
문제의 로직에 방향성이 맞는지 

### 상세 내용
![image](https://user-images.githubusercontent.com/66407386/178543969-b1bea7fa-a291-46c2-b8c6-8982f6a9a637.png)

> 참외 밭의 Xmⁿ을 통해서 1m² * 7 하여 결과 출력은 한다.
> 글쓴이가 생각한 공식 하지만 입력 방식으로 받는 내용을 토대로 한다면 아래와 같은 방식으로는 문제가 있을 것으로 예상
> - (Big가로 * Big세로) - (Small가로 * Small세로)  * 7 = 결과 값
> - (160 * 50) - (60 * 20) * 7 = 47600

제가 이해한 것이 맞는 부분인지? 아니면 조금 수정을 해야 하는 지 조언을 얻고자 합니다.

## 문제 출처
[백준 2477번 참외밭](https://www.acmicpc.net/problem/2477)

**Comment by dnwlsrla40** [comment]
네 생각하시는 방법이 맞습니다. 언급하신 것처럼 입력 방식을 위의 공식에 대입하는 과정이 중요한 것 같습니다.

**Comment by gkfgran5037** [comment]
넵 맞습니다!
6각형 특성상 정사각형에 작은 사각형이 들어간 모습입니다. 그점 고려해서 코드 짜면 됩니다~

**Comment by hongcoding94** [comment]
@dnwlsrla40  @gkfgran5037 두분의 코멘트 감사합니다!! 
덕분에 해결하였습니다
