### ISSUE TITLE
6주차 백준 2776번 암기왕

### ISSUE THREAD

**Issue by hongcoding94** [psStudy6/psStudy#61]
## 질문 유형
문제의 설명이 이해가지 않습니다.

### 상세 내용
![image](https://user-images.githubusercontent.com/66407386/180672645-4134c316-1126-4e9f-a4b2-461899ff915b.png)

해당 본문 내용을 읽어보면 
- >  ‘수첩2’에 적혀있는 순서대로, 각각의 수에 대하여, **‘수첩1’에 있으면 1을, 없으면 0을 출력**하는 프로그램을 작성
- > 글쓴이가 생각하는 정상적인 출력 숫자 → 0 1 0 0 1 
- > 하지만 본문 내용 출력 함을 보면 1 1 0 0 1 로 표기 되어 있음

이라고 나와있는데 그림에 표기된부분이 잘못 되었음에도 1로 표기 되어 이상함을 느껴서 
문제의 설명을 제가 잘 못 알고 있는 듯하여 여쭤보고 싶습니다. 

## 문제 출처
https://www.acmicpc.net/problem/2776

**Comment by gkfgran5037** [comment]
수첩1 : 4 1 5 2 3
수첩2 : 1 3 7 9 5

수첩1은 실제 봤던 정수를, 수첩2는 연종이 봤다는 정수입니다. 수첩2의 숫자가 수첩1에 있으면 1을 없으면 0입니다.

1은 있으므로 1
3은 있으므로 1
7은 없으므로 0
9는 없으므로 0
5는 있으므로 1

**Comment by hongcoding94** [comment]
@gkfgran5037 아..! 제가 반대로 생각을 했었군요 
문제 이해 해결 했습니다.
수첩 1기준이 아닌 수첩 2로 처리하는 방식 다시한번 이해했습니다 
@gkfgran5037 감사합니다
