### ISSUE TITLE
6주차 백준 9372번 상근이의 여행

### ISSUE THREAD

**Issue by hongcoding94** [psStudy6/psStudy#62]
## 질문 유형
문제의 설명이 이해가지 않습니다.

### 상세 내용
![image](https://user-images.githubusercontent.com/66407386/180677919-bfedc7af-3124-40e3-80cc-5bbd63129013.png)

아래 사항을 봤을때 
 - 1번(testCaseNumber) : 1번째 줄에는 국가의 수 N(2 ≤ N ≤ 1 000)과 비행기의 종류 M(1 ≤ M ≤ 10 000) 가 주어진다.
 - 2번(왕복 횟수?) : 이후 M개의 줄에 a와 b 쌍들이 입력된다. a와 b를 왕복하는 비행기가 있다는 것을 의미한다.
 
여기서 2번째의 왕복 횟수의 개념이 무슨 의미로 말하는지 이해가 되지 않습니다. 
추측하건데 
> A → B  / B ← A 이런 개념인지 아니면  <br/> 다른 방법인지 여쭤보고싶습니다.

## 문제 출처
https://www.acmicpc.net/problem/9372

**Comment by dnwlsrla40** [comment]
위 예제를 예시로 하면
3 3 -> 국가 / 비행기(수)
1 2 -> 1번 국가와 2번 국가를 왕복하는 ( 1->2, 2->1 둘 다 가능한) 비행기가 있다.
인 것 같습니다

**Comment by hongcoding94** [comment]
@dnwlsrla40  감사합니다 덕분에 이해했습니다.
문제 풀어보고 모르는 부분이 있다면 여쭤보도록하겠습니다!

**Comment by hongcoding94** [comment]
@everyone 해결했습니다.
