### ISSUE TITLE
6주차 9322번 철벽보한 알고림즘

### ISSUE THREAD

**Issue by hongcoding94** [psStudy6/psStudy#63]
## 질문유형
문제가 이해가 되지 않습니다.

### 상세 내용
![image](https://user-images.githubusercontent.com/66407386/180698392-1d124e70-76cf-4921-93ed-63cf3f6e62ba.png)

위 그림처럼 해당 부분들의 어떻게 들어가서 처리하는 방식은 이해가 되지만 해당 데이터가 없이 
어떻게 저런 데이터 형식으로 들어가는 지 이해가 되지 않습니다. 

## 문제 출처
https://www.acmicpc.net/problem/9322

**Comment by dnwlsrla40** [comment]
저 위의 P는 그냥 저 규칙을 적용한 암호문 예시 입니다. (암호문은 제 1 공개키의 단어와 상관없습니다. 평문과 상관)

문제 내용은 아래와 같습니다.
제 1 공개키(4 단어로 이루어짐)
A B C D

제 2 공개키 (제 1 공개키의 단어 재배열)

1번 단어 -> 2번 단어 위치
2번 단어 -> 3번 단어 위치
3번 단어 -> 4번 단어 위치
4번 단어 -> 1번 단어 위치

D A B C 가 제2 공개키로 나옴

암호문 (평문을 제 2 공개키를 만든 규칙의 반대로 재배치)

즉, 평문을 
1번 단어 -> 2번 단어 위치
2번 단어 -> 3번 단어 위치
3번 단어 -> 4번 단어 위치
4번 단어 -> 1번 단어 위치
이 규칙을 적용해서 만든 것이 암호문 

C B A P

이므로 평문을 구하려면,
2번 단어 -> 1번 단어 위치
3번 단어 -> 2번 단어 위치
4번 단어 -> 3번 단어 위치
1번 단어 -> 4번 단어 위치
로 이동하면 나옵니다.

B A P C

**Comment by hongcoding94** [comment]
@dnwlsrla40 감사합니다 정말로 지문이 이해가 되지 않았는데 
상세한 설명 덕분에 이해하여 풀 수 있었습니다 감사합니다. ㅠㅠ
